/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import javax.swing.JOptionPane;
import model.Encounter;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author sujay
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientJPanel
     */
    PatientDirectory patientList;
    public CreatePatientJPanel(PatientDirectory patientList) {
        initComponents();
        this.patientList = patientList;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAge = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        lblPhNo = new javax.swing.JLabel();
        txtPhNo = new javax.swing.JTextField();
        lblHouse = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtHouse = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblCommuity = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        btnSaveDetails = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblInsurance = new javax.swing.JLabel();
        txtInsurance = new javax.swing.JTextField();

        setBackground(new java.awt.Color(236, 253, 255));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblCity.setText("City :");

        lblGender.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblGender.setText("Gender :");

        lblPhNo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblPhNo.setText("Phone Number :");

        lblHouse.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblHouse.setText("House Number :");

        lblTitle.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Patient Details");

        lblFirstName.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblFirstName.setText("First Name :");

        lblCommuity.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblCommuity.setText("Community :");

        btnSaveDetails.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnSaveDetails.setText("Save");
        btnSaveDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDetailsActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblAge.setText("Age :");

        lblLastName.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblLastName.setText("Last Name :");

        lblInsurance.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblInsurance.setText("Patient ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhNo)
                                .addGap(31, 31, 31)
                                .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCommuity, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHouse, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInsurance)
                                    .addComponent(lblGender))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(btnSaveDetails)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblAge))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(567, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblTitle)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsurance)
                    .addComponent(txtInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhNo)
                    .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouse)
                    .addComponent(txtHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommuity)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveDetails)
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnSaveDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDetailsActionPerformed
        // TODO add your handling code here:
        try {
        String personFirstName = txtFirstName.getText();
        String personLastName = txtLastName.getText();
        int age = Integer.parseInt(txtAge.getText());
        String gender = txtGender.getText();
        String insuranceId = txtInsurance.getText();
        long phNo = Long.parseLong(txtPhNo.getText());
        int houseNumber = Integer.parseInt(txtHouse.getText());
        String communityName = txtCommunity.getText();
        String cityName = txtCity.getText();
        String encounterDate;
        
        Patient pat = patientList.createPatient();
        
        pat.setPersonFirstName(personFirstName);
        pat.setPersonLastName(personLastName);
        pat.setAge(age);
        pat.setGender(gender);
        pat.setPatientId(insuranceId);
        pat.setPhNo(phNo);
        pat.setHouseNumber(houseNumber);
        pat.setCommunityName(communityName);
        pat.setCityName(cityName);
        } catch(Exception e) {}
        
        JOptionPane.showMessageDialog(this, "Patient Details Added Successfully.");
        
        txtFirstName.setText("");
        txtLastName.setText("");
        txtGender.setText("");
        txtInsurance.setText("");
        txtPhNo.setText("");
        txtHouse.setText("");
        txtCommunity.setText("");
        txtAge.setText("");
        txtCity.setText("");
        
//        if(txtFirstName.getText() == null || "".equals(txtFirstName.getText())){
//            JOptionPane.showMessageDialog(this, "Please enter valid Manufacturer Name !!!");
//        }
//        else if(txtLastName.getText() == null || "".equals(txtLastName.getText())){
//            JOptionPane.showMessageDialog(this, "Please enter valid Model Name !!!");
//        }
//        else if(txtCommunity.getText() == null || "".equals(txtCommunity.getText())){
//            JOptionPane.showMessageDialog(this, "Please enter valid Manufacturing Year !!!");
//        }
//        else if(txtAge.getText() == null || "".equals(txtAge.getText())){
//            JOptionPane.showMessageDialog(this, "Please enter valid Number of Seats !!!");
//        }
//        else if(txtHouse.getText() == null || "".equals(txtHouse.getText())){
//            JOptionPane.showMessageDialog(this, "Please enter valid City !!!");
//        }
//        else if(txtGender.getText() == null || "".equals(txtGender.getText())){
//            JOptionPane.showMessageDialog(this, "Please enter valid License Plate Number !!!");
//        }
//        else if(!list.isUnique(txtGender.getText())){
//            JOptionPane.showMessageDialog(this, "Please enter Unique License Plate Number !!!");
//        }
//
//        else {
//            

        

    }//GEN-LAST:event_btnSaveDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDetails;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommuity;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtInsurance;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhNo;
    // End of variables declaration//GEN-END:variables
}
