/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.City;
import model.Community;
import model.Encounter;
import model.EncounterHistory;
import model.PatientDirectory;
import model.VitalSigns;

/**
 *
 * @author sujay
 */
public class MainJFrame extends javax.swing.JFrame {
    PatientDirectory patientList;
    Community houseList;
    City communityList;
    Encounter encounter;
    VitalSigns vitalSigns;
    EncounterHistory encounterHistory;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        patientList = new PatientDirectory();
        encounter = new Encounter();
        vitalSigns = new VitalSigns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPaneHome = new javax.swing.JSplitPane();
        controlPanelHospital = new javax.swing.JPanel();
        btnCreatePatient = new javax.swing.JButton();
        btnVitalSigns = new javax.swing.JButton();
        btnViewEncounter = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        lblCaption = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanelHospital.setBackground(java.awt.Color.black);

        btnCreatePatient.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnCreatePatient.setText("Create Patient ");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        btnVitalSigns.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        btnVitalSigns.setText("Add Vital Signs");
        btnVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalSignsActionPerformed(evt);
            }
        });

        btnViewEncounter.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        btnViewEncounter.setText("View Encounter Details");
        btnViewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelHospitalLayout = new javax.swing.GroupLayout(controlPanelHospital);
        controlPanelHospital.setLayout(controlPanelHospitalLayout);
        controlPanelHospitalLayout.setHorizontalGroup(
            controlPanelHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelHospitalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVitalSigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreatePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        controlPanelHospitalLayout.setVerticalGroup(
            controlPanelHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelHospitalLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(btnCreatePatient)
                .addGap(18, 18, 18)
                .addComponent(btnVitalSigns)
                .addGap(18, 18, 18)
                .addComponent(btnViewEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        splitPaneHome.setLeftComponent(controlPanelHospital);

        workArea.setBackground(new java.awt.Color(236, 253, 255));

        lblCaption.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lblCaption.setForeground(java.awt.Color.gray);
        lblCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaption.setText("We Care for You !!!");

        lblTitle.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Dr. Johnson's Hospital");

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1344, Short.MAX_VALUE)
                    .addComponent(lblCaption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaption)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        splitPaneHome.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneHome)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneHome)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        CreatePatientJPanel createPanel = new CreatePatientJPanel(patientList, houseList, communityList );
        splitPaneHome.setRightComponent(createPanel);
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalSignsActionPerformed
        // TODO add your handling code here:
        AddVitalSignsJPanel vitalsPanel = new AddVitalSignsJPanel(patientList, encounter, vitalSigns);
        splitPaneHome.setRightComponent(vitalsPanel);
    }//GEN-LAST:event_btnVitalSignsActionPerformed

    private void btnViewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncounterActionPerformed
        // TODO add your handling code here:
        ViewEncountersJPanel viewPanel = new ViewEncountersJPanel(patientList, encounter, vitalSigns, encounterHistory);
        splitPaneHome.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewEncounterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnViewEncounter;
    private javax.swing.JButton btnVitalSigns;
    private javax.swing.JPanel controlPanelHospital;
    private javax.swing.JLabel lblCaption;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSplitPane splitPaneHome;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

   
}
