

package userinterface.RestaurantAdminRole;


import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount ua;
    
    /** Creates new form AdminWorkAreaJPanel
     * @param userProcessContainer */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount ua, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.system = system;
      
        lblResName.setText(ua.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleResAdmin = new javax.swing.JLabel();
        btnResInfo = new javax.swing.JButton();
        btnManageMenu = new javax.swing.JButton();
        btnManageOrders = new javax.swing.JButton();
        lblResNameTitle = new javax.swing.JLabel();
        lblResName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 156, 52));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleResAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleResAdmin.setText("Restaurant Admin");
        add(titleResAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        btnResInfo.setText("Manage Restaurant Info");
        btnResInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResInfoActionPerformed(evt);
            }
        });
        add(btnResInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 160, -1));

        btnManageMenu.setText("Manage Menu");
        btnManageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMenuActionPerformed(evt);
            }
        });
        add(btnManageMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, -1));

        btnManageOrders.setText("Manage Orders");
        btnManageOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrdersActionPerformed(evt);
            }
        });
        add(btnManageOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, -1));

        lblResNameTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResNameTitle.setText("Restaurant Name :");
        add(lblResNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 190, 30));

        lblResName.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        add(lblResName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnResInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResInfoActionPerformed
        // TODO add your handling code here:
        ManageRestaurantInfoJPanel manageInfo = new ManageRestaurantInfoJPanel(userProcessContainer, ua, system);
        userProcessContainer.add("Manage Restaurant Info",manageInfo);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnResInfoActionPerformed

    private void btnManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMenuActionPerformed
        ManageMenuJPanel manageMenu = new ManageMenuJPanel(userProcessContainer, ua, system);
        userProcessContainer.add("Manage Restaurents",manageMenu);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageMenuActionPerformed

    private void btnManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrdersActionPerformed
        ManageOrdersJPanel manageOrder = new ManageOrdersJPanel(userProcessContainer, ua, system);
        userProcessContainer.add("Manage Orders", manageOrder);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrdersActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageMenu;
    private javax.swing.JButton btnManageOrders;
    private javax.swing.JButton btnResInfo;
    private javax.swing.JLabel lblResName;
    private javax.swing.JLabel lblResNameTitle;
    private javax.swing.JLabel titleResAdmin;
    // End of variables declaration//GEN-END:variables
    
}
