/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sujay
 */
public class ManageRestaurantInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantInfoJPanel
     */
    EcoSystem system;
    JPanel userProcessContainer;
    UserAccount account;
    
    public ManageRestaurantInfoJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system) {
        initComponents();
        initComponents();
        this.account=account;
        this.system=system;
        this.userProcessContainer=userProcessContainer;
        
        txtResName.setEnabled(false);
        txtResAddress.setEnabled(false);
        txtResPhNum.setEnabled(false);
        txtResCuisine.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        populateFields();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblResName = new javax.swing.JLabel();
        lblResAddress = new javax.swing.JLabel();
        lblResPhNum = new javax.swing.JLabel();
        txtResName = new javax.swing.JTextField();
        txtResAddress = new javax.swing.JTextField();
        txtResPhNum = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        titleResInfo = new javax.swing.JLabel();
        lblResCuisine = new javax.swing.JLabel();
        txtResCuisine = new javax.swing.JTextField();

        setBackground(new java.awt.Color(252, 156, 52));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblResName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResName.setText("Restaurant Name :");

        lblResAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResAddress.setText("Restaurant Address :");

        lblResPhNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResPhNum.setText("Restaurant Phone Number :");

        txtResName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResNameActionPerformed(evt);
            }
        });

        txtResAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResAddressActionPerformed(evt);
            }
        });

        txtResPhNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResPhNumActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        titleResInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleResInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleResInfo.setText("Manage Restaurant Info");

        lblResCuisine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResCuisine.setText("Cuisine :");

        txtResCuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResCuisineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblResPhNum)
                                    .addComponent(lblResAddress)
                                    .addComponent(lblResName)
                                    .addComponent(lblResCuisine))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtResName)
                                    .addComponent(txtResAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtResPhNum, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtResCuisine))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(titleResInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnBack)
                .addGap(43, 43, 43)
                .addComponent(titleResInfo)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResPhNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResName)
                            .addComponent(txtResName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResAddress)
                            .addComponent(txtResAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblResPhNum)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResCuisine)
                    .addComponent(txtResCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtResNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResNameActionPerformed

    private void txtResAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResAddressActionPerformed

    private void txtResPhNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResPhNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResPhNumActionPerformed

    private void txtResCuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResCuisineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResCuisineActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtResName.getText();
        String address = txtResAddress.getText();
        String number = txtResPhNum.getText();
        String cuisine = txtResCuisine.getText();
        
        try {
             if(name==null || name.isEmpty()){
                throw new NullPointerException("Restaurant Name Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Restaurant Name Field cannot be Empty !!!");        
            return;   
        }
        
        try {
             if(address==null || address.isEmpty()){
                throw new NullPointerException("Restaurant Address Field cannot be Empty !!!");    
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Restaurant Address Field cannot be Empty !!!");          
            return;   
        }
        
         try {
             
            if(number==null || number.isEmpty()){
                throw new NullPointerException("Restaurant Phone Number Field cannot be Empty !!!");
            }else if(Pattern.matches("^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$", number) == false){
                throw new Exception("Enter a Valid Phone number !!!");
            }     
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Restaurant Phone Number Field cannot be Empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a Valid Phone number !!!");
            return;
        }
         
        try {
             if(cuisine==null || cuisine.isEmpty()){
                throw new NullPointerException("Restaurant Cuisine Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Restaurant Cuisine Field cannot be Empty !!!");        
            return;   
        }
        
        for(Restaurant res:system.getRestaurantDirectory().getRestaurantList()){
           if(res.getUserName().equals(account.getUsername())){
                system.getRestaurantDirectory().updateRestaurantInfo(res,name, number, address, cuisine);
            }
        }
        
        txtResName.setEnabled(false);
        txtResAddress.setEnabled(false);
        txtResPhNum.setEnabled(false);
        txtResCuisine.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtResName.setEnabled(true);
        txtResAddress.setEnabled(true);
        txtResPhNum.setEnabled(true);
        txtResCuisine.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblResAddress;
    private javax.swing.JLabel lblResCuisine;
    private javax.swing.JLabel lblResName;
    private javax.swing.JLabel lblResPhNum;
    private javax.swing.JLabel titleResInfo;
    private javax.swing.JTextField txtResAddress;
    private javax.swing.JTextField txtResCuisine;
    private javax.swing.JTextField txtResName;
    private javax.swing.JTextField txtResPhNum;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        for(Restaurant res:system.getRestaurantDirectory().getRestaurantList()){
           if(res.getUserName().equals(account.getUsername())){
               txtResName.setText(res.getResName());
               txtResAddress.setText(res.getResAddress());
               txtResPhNum.setText(res.getResPhNum());
               txtResCuisine.setText(res.getResCuisine());
            }
    }
}
}
