/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import javax.swing.JPanel;

/**
 *
 * @author sujay
 */
public class ManageRestaurantsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantsJPanel
     * 
     */
        private JPanel userProcessContainer;
        private EcoSystem system;
    public ManageRestaurantsJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateRestaurantTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurants = new javax.swing.JTable();
        txtResName = new javax.swing.JTextField();
        btnResBack = new javax.swing.JButton();
        btnSubmitRestaurant = new javax.swing.JButton();
        lblResName = new javax.swing.JLabel();
        txtResUsername = new javax.swing.JTextField();
        lblResPassword = new javax.swing.JLabel();
        txtResPassword = new javax.swing.JPasswordField();
        btnUpdateRestaurant = new javax.swing.JButton();
        btnDeleteRestaurant = new javax.swing.JButton();
        lblResUsername = new javax.swing.JLabel();
        titleManageRestaurants = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRestaurants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Restaurant Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRestaurants);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 496, 91));
        add(txtResName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 144, -1));

        btnResBack.setText("<< Back");
        btnResBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResBackActionPerformed(evt);
            }
        });
        add(btnResBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        btnSubmitRestaurant.setText("Submit");
        btnSubmitRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRestaurantActionPerformed(evt);
            }
        });
        add(btnSubmitRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        lblResName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResName.setText("Restaurant Name:");
        add(lblResName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));
        add(txtResUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 144, -1));

        lblResPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResPassword.setText("Password:");
        add(lblResPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        txtResPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResPasswordActionPerformed(evt);
            }
        });
        add(txtResPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 144, -1));

        btnUpdateRestaurant.setText("Update");
        btnUpdateRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRestaurantActionPerformed(evt);
            }
        });
        add(btnUpdateRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        btnDeleteRestaurant.setText("Delete");
        btnDeleteRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRestaurantActionPerformed(evt);
            }
        });
        add(btnDeleteRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        lblResUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResUsername.setText("Username:");
        add(lblResUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, 20));

        titleManageRestaurants.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleManageRestaurants.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleManageRestaurants.setText("Manage Restaurants");
        add(titleManageRestaurants, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 816, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnResBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResBackActionPerformed
        
    }//GEN-LAST:event_btnResBackActionPerformed

    private void btnSubmitRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRestaurantActionPerformed

    }//GEN-LAST:event_btnSubmitRestaurantActionPerformed

    private void txtResPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResPasswordActionPerformed

    private void btnUpdateRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRestaurantActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnUpdateRestaurantActionPerformed

    private void btnDeleteRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRestaurantActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDeleteRestaurantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteRestaurant;
    private javax.swing.JButton btnResBack;
    private javax.swing.JButton btnSubmitRestaurant;
    private javax.swing.JButton btnUpdateRestaurant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResName;
    private javax.swing.JLabel lblResPassword;
    private javax.swing.JLabel lblResUsername;
    private javax.swing.JTable tblRestaurants;
    private javax.swing.JLabel titleManageRestaurants;
    private javax.swing.JTextField txtResName;
    private javax.swing.JPasswordField txtResPassword;
    private javax.swing.JTextField txtResUsername;
    // End of variables declaration//GEN-END:variables

    private void populateRestaurantTable() {
       
    }
}
