/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author sujay
 */

public class ManageCustomersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomersJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    UserAccount user;
    public ManageCustomersJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateCustomersTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        txtCusName = new javax.swing.JTextField();
        btnCusBack = new javax.swing.JButton();
        btnSubmitCustomer = new javax.swing.JButton();
        lblCusName = new javax.swing.JLabel();
        txtCusUsername = new javax.swing.JTextField();
        lblCusPassword = new javax.swing.JLabel();
        txtCusPassword = new javax.swing.JPasswordField();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        lblCusUsername = new javax.swing.JLabel();
        titleManageCustomers = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 496, 91));
        add(txtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 144, -1));

        btnCusBack.setText("<< Back");
        btnCusBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusBackActionPerformed(evt);
            }
        });
        add(btnCusBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        btnSubmitCustomer.setText("Submit");
        btnSubmitCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitCustomerActionPerformed(evt);
            }
        });
        add(btnSubmitCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        lblCusName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCusName.setText("Customer Name:");
        add(lblCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));
        add(txtCusUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 144, -1));

        lblCusPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCusPassword.setText("Password:");
        add(lblCusPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        txtCusPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusPasswordActionPerformed(evt);
            }
        });
        add(txtCusPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 144, -1));

        btnUpdateCustomer.setText("Update");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });
        add(btnUpdateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        btnDeleteCustomer.setText("Delete");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });
        add(btnDeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        lblCusUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCusUsername.setText("Username:");
        add(lblCusUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, 20));

        titleManageCustomers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleManageCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleManageCustomers.setText("Manage Customers");
        add(titleManageCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 816, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCusBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusBackActionPerformed

    }//GEN-LAST:event_btnCusBackActionPerformed

    private void btnSubmitCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitCustomerActionPerformed

    }//GEN-LAST:event_btnSubmitCustomerActionPerformed

    private void txtCusPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusPasswordActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void populateCustomersTable() {
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCusBack;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnSubmitCustomer;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCusName;
    private javax.swing.JLabel lblCusPassword;
    private javax.swing.JLabel lblCusUsername;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JLabel titleManageCustomers;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JPasswordField txtCusPassword;
    private javax.swing.JTextField txtCusUsername;
    // End of variables declaration//GEN-END:variables
}
